import os
import json
from datetime import datetime
from pathlib import Path

# plain text and JSON incident report exporting helper

# Detect Streamlit Cloud vs. local environment
if os.path.exists("/mount/src/ai-soc-analyst"):
    REPORTS_DIR = Path("/tmp/reports")
else:
    REPORTS_DIR = Path(__file__).parent / "reports"
REPORTS_DIR.mkdir(exist_ok=True)




def generate_text_report(alerts: list[dict], title: str = "SOC Incident Report") -> str:
    """
    Generates a formatted, human-readable plain-text incident report from
    a list of triaged alert records. Used for email briefings, shift handovers,
    and documentation during post-incident reviews.

    Args:
        alerts : List of alert dictionaries retrieved from the database.
        title  : Optional custom title for the report header.

    Returns:
        Multi-line string containing the full formatted report.
    """
    now = datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")
    sep = "=" * 70
    thin_sep = "-" * 70

    # --- Build severity counts for the executive summary ---
    severity_counts = {"Critical": 0, "High": 0, "Medium": 0, "Low": 0, "Unknown": 0}
    for a in alerts:
        sev = str(a.get("severity", "Unknown")).strip()
        if sev in severity_counts:
            severity_counts[sev] += 1
        else:
            severity_counts["Unknown"] += 1

    # --- Build report header ---
    lines = [
        sep,
        f"  {title.upper()}",
        f"  Generated: {now}",
        f"  Total Alerts: {len(alerts)}",
        sep,
        "",
        "EXECUTIVE SUMMARY",
        thin_sep,
        "  The following table summarizes alert severity distribution:",
        "",
        f"  {'Severity':<12} {'Count':<8} {'Bar'}",
        f"  {'-'*12} {'-'*8} {'-'*20}",
    ]

    # Severity bar chart (ASCII art)
    for sev, count in severity_counts.items():
        bar = "█" * count
        lines.append(f"  {sev:<12} {count:<8} {bar}")

    lines += [
        "",
        "RISK OVERVIEW",
        thin_sep,
        f"  High/Critical Events : {severity_counts['Critical'] + severity_counts['High']}",
        f"  Medium Events        : {severity_counts['Medium']}",
        f"  Low/Info Events      : {severity_counts['Low']}",
        "",
        sep,
        "DETAILED ALERT LOG",
        sep,
        ""
    ]

    # --- Alert detail blocks ---
    for idx, alert in enumerate(alerts, start=1):
        vt = {}
        try:
            vt = json.loads(alert.get("vt_result") or "{}")
        except (json.JSONDecodeError, TypeError):
            pass

        lines += [
            f"[ALERT #{idx}]  ID: {alert.get('id', 'N/A')}",
            thin_sep,
            f"  Timestamp     : {alert.get('timestamp', 'N/A')}",
            f"  Event Type    : {alert.get('event_type', 'N/A')}",
            f"  Severity      : {alert.get('severity', 'N/A')}",
            f"  Source IP     : {alert.get('source_ip', 'N/A')}",
            f"  Destination   : {alert.get('dest_ip', 'N/A')}",
            f"  Status        : {alert.get('status', 'New')}",
            "",
            f"  [ VirusTotal Intelligence ]",
            f"    Verdict        : {vt.get('verdict', 'N/A')}",
            f"    Detections     : {vt.get('detections', 'N/A')}",
            f"    Country        : {vt.get('country', 'N/A')}",
            f"    Owner          : {vt.get('owner', 'N/A')}",
            "",
            f"  [ MITRE ATT&CK Mapping ]",
            f"    {alert.get('mitre_tag', 'N/A')}",
            "",
            f"  [ AI Triage Summary ]",
        ]

        # Word-wrap the AI summary to 60 chars per line
        summary = alert.get("ai_summary") or "No AI summary available."
        for chunk in _wrap_text(summary, width=62):
            lines.append(f"    {chunk}")

        lines += [
            "",
            f"  [ Recommended Response ]",
        ]
        response = alert.get("response_plan") or "No response plan available."
        for chunk in _wrap_text(response, width=62):
            lines.append(f"    {chunk}")

        lines += ["", ""]

    # --- Footer ---
    lines += [
        sep,
        "END OF REPORT",
        f"Classification: INTERNAL / SOC USE ONLY",
        f"Report generated by ai-soc-analyst triage system.",
        sep,
    ]

    return "\n".join(lines)




def generate_json_report(alerts: list[dict], title: str = "SOC Incident Report") -> dict:
    """
    Produces a structured JSON report suitable for forwarding to a SIEM,
    ticketing system, or management dashboard API endpoint.

    Each alert entry is normalized and enriched with metadata for
    downstream consumption by other security tooling.

    Args:
        alerts : List of alert dictionaries from the database.
        title  : Optional report title string.

    Returns:
        A JSON-serializable dictionary containing full report data.
    """
    total = len(alerts)
    critical_count = sum(1 for a in alerts if "Critical" in str(a.get("severity", "")))
    high_count = sum(1 for a in alerts if "High" in str(a.get("severity", "")))
    malicious_count = sum(
        1 for a in alerts
        if "Malicious" in str(json.loads(a.get("vt_result") or "{}").get("verdict", ""))
    )

    normalized_alerts = []
    for a in alerts:
        vt = {}
        try:
            vt = json.loads(a.get("vt_result") or "{}")
        except (json.JSONDecodeError, TypeError):
            pass

        normalized_alerts.append({
            "id": a.get("id"),
            "timestamp": a.get("timestamp"),
            "event_type": a.get("event_type"),
            "severity": a.get("severity"),
            "source_ip": a.get("source_ip"),
            "destination": a.get("dest_ip"),
            "status": a.get("status", "New"),
            "vt_verdict": vt.get("verdict"),
            "vt_country": vt.get("country"),
            "vt_detections": vt.get("detections"),
            "mitre_tag": a.get("mitre_tag"),
            "ai_summary": a.get("ai_summary"),
            "response_plan": a.get("response_plan"),
        })

    return {
        "report_title": title,
        "generated_at": datetime.utcnow().isoformat() + "Z",
        "summary": {
            "total_alerts": total,
            "critical": critical_count,
            "high": high_count,
            "malicious_ips_flagged": malicious_count,
        },
        "alerts": normalized_alerts,
    }




def save_text_report(content: str, filename: str = None) -> str:
    """
    Writes a text report to the /reports directory.

    Args:
        content  : The report string to write.
        filename : Optional filename override. Auto-generated if None.

    Returns:
        Absolute path to the saved file.
    """
    if not filename:
        ts = datetime.utcnow().strftime("%Y%m%d_%H%M%S")
        filename = f"soc_report_{ts}.txt"

    path = REPORTS_DIR / filename
    path.write_text(content, encoding="utf-8")
    return str(path)


def save_json_report(data: dict, filename: str = None) -> str:
    """
    Writes a JSON report to the /reports directory.

    Args:
        data     : The report dictionary to serialize.
        filename : Optional filename override. Auto-generated if None.

    Returns:
        Absolute path to the saved JSON file.
    """
    if not filename:
        ts = datetime.utcnow().strftime("%Y%m%d_%H%M%S")
        filename = f"soc_report_{ts}.json"

    path = REPORTS_DIR / filename
    path.write_text(json.dumps(data, indent=2), encoding="utf-8")
    return str(path)


def list_saved_reports() -> list[dict]:
    """
    Returns metadata for all previously generated reports.

    Returns:
        List of dicts with keys: name, path, size_kb, modified.
    """
    reports = []
    for f in sorted(REPORTS_DIR.iterdir(), key=lambda p: p.stat().st_mtime, reverse=True):
        if f.suffix in (".txt", ".json"):
            stat = f.stat()
            reports.append({
                "name": f.name,
                "path": str(f),
                "size_kb": round(stat.st_size / 1024, 2),
                "modified": datetime.fromtimestamp(stat.st_mtime).strftime("%Y-%m-%d %H:%M")
            })
    return reports




def _wrap_text(text: str, width: int = 70) -> list[str]:
    """
    Wraps a long string into a list of shorter lines for report formatting.
    Simple word-based wrapping — does not break in the middle of words.

    Args:
        text  : The string to wrap.
        width : Maximum characters per line.

    Returns:
        List of wrapped line strings.
    """
    words = text.split()
    lines, current = [], ""
    for word in words:
        if len(current) + len(word) + 1 <= width:
            current += (" " if current else "") + word
        else:
            if current:
                lines.append(current)
            current = word
    if current:
        lines.append(current)
    return lines if lines else [""]
